name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: GLNKDEMO # Replace this with your Azure Web App name

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write # Required for pushing images to GitHub Container Registry

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }} # Make sure this secret is set in your repo

      # Build and push the Docker image to GitHub Container Registry
      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./back-end # Specify the path to the back-end directory
          file: ./back-end/Dockerfile # Specify the path to the Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/glnkdemo:${{ github.sha }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Ensure this secret is correctly set in your repo

      # Deploy the Docker image to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Ensure this secret is set in your repo
          images: 'ghcr.io/${{ github.actor }}/glnkdemo:${{ github.sha }}'
