name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: GLNKDEMO # Replace this with your actual Azure Web App name

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write # Required for pushing images to GitHub Container Registry

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Set up Docker Buildx for advanced builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }} # Ensure this secret is correctly set in your repo

      # Lowercase the repository name for consistency
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # Build and push the Docker container image to GitHub Container Registry
      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./back-end # Specify the path to the back-end directory as the build context
          file: ./back-end/Dockerfile # Specify the correct path to the Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Lowercase the repository name for consistency
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # Deploy the Docker image to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Ensure this secret is correctly set in your repo
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
